name: Build-Apk

on:
  workflow_dispatch:

  push:
    branches:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4

      - run: chmod 777 ./gradlew
      - run: ./gradlew app:assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: app/build/outputs

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: app/build/outputs/apk/release
